#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require "./lib/lexer.rb"
require "./lib/keywords.rb"

class ZLanguageParser < Racc::Parser

module_eval(<<'...end z_language_parser.y/module_eval...', 'z_language_parser.y', 67)
  def parse str
    @table = Hash.new
    @lexer = make_lexer str
    do_parse
  end

  def next_token
    last = @lexer.next_token
    puts last[0].to_s + ":\t" + last[1].to_s 
    last
  end

  def make_lexer str
    lexer = Lexer.new

    lexer.add_ignore(/\s+/)
    # lexer.add_ignore(/#[^\n]+/)

    keywords.each do |kw|
      lexer.add_keyword kw
    end
    
    keywords_space.each do |kw|
      lexer.add_keyword_space kw
    end

    lexer.add_token(/-/, :NEGATIVE)
    lexer.add_token(/\(/, :L_PARE)
    lexer.add_token(/\)/, :R_PARE)
    lexer.add_token(/\./, :POINT)
    lexer.add_token(/\d+/, :NUMBER)
    lexer.add_token(/[^\(^\)^\n^=]+/, :STRING)

    lexer.start str
    return lexer
  end

...end z_language_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     7,    26,     9,    10,    11,     7,    12,     9,    10,    11,
    14,    12,     9,    10,    11,    13,    12,    13,    28,    29,
    13,    51,     9,    10,    11,    13,    12,    19,    68,    52,
    83,    86,   101,    28,    29,    13,    52,    20,    84,    87,
    52,    36,    37,    38,    39,    40,    41,    42,    43,    36,
    37,    38,    39,    40,    41,    42,    43,    66,    16,    21,
    17,    22,    52,    28,    29,    28,    29,    23,    24,    13,
    32,    45,    45,    45,    48,    13,    50,    13,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64,    65,
    13,    45,    74,    75,    45,    45,    45,    45,    85,    88,
    89,    90,    91,    92,    17,    13,    45,    13,    98,    99,
   100,    45,   103 ]

racc_action_check = [
     0,    16,    68,    68,    68,     3,    68,     0,     0,     0,
     1,     0,     3,     3,     3,    68,     3,     7,    16,    16,
     0,    30,    81,    81,    81,     3,    81,     8,    53,    30,
    71,    73,    97,    55,    55,    81,    53,     9,    71,    73,
    97,    19,    19,    19,    19,    19,    19,    19,    19,    54,
    54,    54,    54,    54,    54,    54,    54,    49,     6,    10,
     6,    11,    49,    57,    57,    87,    87,    12,    14,    17,
    18,    20,    21,    22,    23,    26,    29,    32,    35,    36,
    37,    38,    39,    40,    41,    42,    43,    44,    46,    47,
    52,    56,    58,    59,    60,    61,    62,    65,    72,    76,
    77,    78,    79,    80,    82,    84,    88,    89,    94,    95,
    96,   100,   102 ]

racc_action_pointer = [
    -3,    10,   nil,     2,   nil,   nil,    56,    -6,    18,    33,
    55,    57,    63,   nil,    68,   nil,    -6,    46,    66,    26,
    48,    49,    50,    69,   nil,   nil,    52,   nil,   nil,    52,
    16,   nil,    54,   nil,   nil,    69,    75,    76,    77,    78,
    79,    80,    81,    82,    82,   nil,    83,    76,   nil,    49,
   nil,   nil,    67,    23,    34,     9,    68,    39,    87,    88,
    71,    72,    73,   nil,   nil,    74,   nil,   nil,    -8,   nil,
   nil,    25,    93,    26,   nil,   nil,    86,    87,    96,    97,
    97,    12,   100,   nil,    82,   nil,   nil,    41,    83,    84,
   nil,   nil,   nil,   nil,   103,   104,    97,    27,   nil,   nil,
    88,   nil,   107,   nil ]

racc_action_default = [
    -2,   -41,    -1,    -3,    -5,    -6,   -41,   -41,   -13,   -41,
   -41,   -41,   -41,   -38,   -41,    -4,   -41,   -34,   -41,   -41,
   -41,   -41,   -41,   -41,   104,    -7,   -34,   -10,   -39,   -41,
   -41,   -35,   -34,   -14,   -15,   -21,   -41,   -41,   -41,   -41,
   -41,   -41,   -41,   -41,   -41,   -37,   -41,   -41,   -19,   -41,
   -40,   -20,   -41,   -41,   -41,   -41,   -41,   -41,   -41,   -41,
   -41,   -41,   -41,   -16,   -17,   -41,    -9,   -36,   -41,   -22,
   -23,   -41,   -41,   -41,   -28,   -29,   -41,   -41,   -41,   -41,
   -41,   -11,   -41,   -24,   -41,   -26,   -27,   -41,   -41,   -34,
   -33,   -18,    -8,   -12,   -41,   -41,   -41,   -41,   -25,   -30,
   -41,   -32,   -41,   -31 ]

racc_goto_table = [
     6,    27,    30,     6,    33,    81,    34,    18,    44,    46,
    47,    49,    80,     2,     1,    25,    15,    53,    81,   nil,
   nil,   nil,   nil,   nil,   nil,    93,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    69,
    71,    70,    73,   nil,    72,   nil,   nil,   nil,    76,    77,
    78,   nil,    67,    79,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    82,   nil,
   nil,   nil,    95,   nil,    97,   nil,    96,   nil,   nil,   nil,
   nil,    82,   nil,   nil,    94,   nil,   nil,   nil,   102 ]

racc_goto_check = [
     6,    10,     8,     6,    12,     5,    13,     6,    14,    14,
    14,     8,     9,     2,     1,     7,     2,     8,     5,   nil,
   nil,   nil,   nil,   nil,   nil,     9,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    12,
    10,    13,    10,   nil,    14,   nil,   nil,   nil,    14,    14,
    14,   nil,     6,    14,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     6,   nil,
   nil,   nil,    10,   nil,     8,   nil,    14,   nil,   nil,   nil,
   nil,     6,   nil,   nil,     6,   nil,   nil,   nil,    14 ]

racc_goto_pointer = [
   nil,    14,    13,   nil,   nil,   -63,     0,    -1,   -15,   -56,
   -15,   nil,   -15,   -13,   -12,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,    31,   nil,   nil,   nil,
   nil,     8,   nil,   nil,   nil,    35 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 27, :_reduce_none,
  0, 27, :_reduce_none,
  1, 28, :_reduce_none,
  2, 28, :_reduce_none,
  1, 29, :_reduce_5,
  1, 29, :_reduce_6,
  3, 30, :_reduce_none,
  7, 30, :_reduce_none,
  3, 33, :_reduce_none,
  1, 33, :_reduce_none,
  1, 35, :_reduce_none,
  2, 35, :_reduce_none,
  1, 31, :_reduce_none,
  3, 31, :_reduce_none,
  3, 31, :_reduce_none,
  4, 37, :_reduce_none,
  4, 37, :_reduce_none,
  6, 37, :_reduce_none,
  3, 37, :_reduce_none,
  4, 37, :_reduce_none,
  1, 39, :_reduce_none,
  3, 39, :_reduce_none,
  3, 39, :_reduce_none,
  4, 38, :_reduce_none,
  6, 38, :_reduce_none,
  4, 41, :_reduce_none,
  4, 41, :_reduce_none,
  3, 41, :_reduce_none,
  3, 41, :_reduce_none,
  6, 41, :_reduce_none,
  8, 41, :_reduce_none,
  6, 41, :_reduce_none,
  4, 41, :_reduce_none,
  0, 34, :_reduce_none,
  1, 34, :_reduce_none,
  3, 34, :_reduce_none,
  1, 40, :_reduce_none,
  1, 32, :_reduce_none,
  1, 36, :_reduce_39,
  2, 36, :_reduce_40 ]

racc_reduce_n = 41

racc_shift_n = 104

racc_token_table = {
  false => 0,
  :error => 1,
  "=" => 2,
  "def" => 3,
  :L_PARE => 4,
  :R_PARE => 5,
  "end" => 6,
  "[" => 7,
  "]" => 8,
  :POINT => 9,
  "text" => 10,
  "img" => 11,
  "form" => 12,
  "," => 13,
  "newline" => 14,
  "times" => 15,
  "url" => 16,
  "size" => 17,
  "bold" => 18,
  "italic" => 19,
  "input" => 20,
  "select" => 21,
  "submit" => 22,
  :STRING => 23,
  :NUMBER => 24,
  :NEGATIVE => 25 }

racc_nt_base = 26

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"=\"",
  "\"def\"",
  "L_PARE",
  "R_PARE",
  "\"end\"",
  "\"[\"",
  "\"]\"",
  "POINT",
  "\"text\"",
  "\"img\"",
  "\"form\"",
  "\",\"",
  "\"newline\"",
  "\"times\"",
  "\"url\"",
  "\"size\"",
  "\"bold\"",
  "\"italic\"",
  "\"input\"",
  "\"select\"",
  "\"submit\"",
  "STRING",
  "NUMBER",
  "NEGATIVE",
  "$start",
  "start",
  "methods",
  "method",
  "define",
  "html",
  "name",
  "variable",
  "array",
  "htmls",
  "number",
  "first",
  "last",
  "attributes",
  "string",
  "attribute" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

module_eval(<<'.,.,', 'z_language_parser.y', 10)
  def _reduce_5(val, _values, result)
     puts '>>>>>>>define' 
    result
  end
.,.,

module_eval(<<'.,.,', 'z_language_parser.y', 11)
  def _reduce_6(val, _values, result)
     puts '>>>>>>>html' 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

module_eval(<<'.,.,', 'z_language_parser.y', 56)
  def _reduce_39(val, _values, result)
     result = val[0].to_i 
    result
  end
.,.,

module_eval(<<'.,.,', 'z_language_parser.y', 57)
  def _reduce_40(val, _values, result)
     result = -(val[1].to_i) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ZLanguageParser

# Run under code if execute by cmd > Ruby "this file"
if $0 == __FILE__
  parser = ZLanguageParser.new
  # Get data for parse from file.
  file_path = ARGV[0] || "sample/example.txt"
  file = File.open(file_path, "rb")
  contents = file.read
  file.close
  # Show what to parse.
  puts "Parsing:\n" + contents.to_s
  puts
  puts 'Result:'
  # Do parse.
  # begin
    parser.parse(contents.to_s)
  # rescue
  #   puts $!
  # end
end
